### ISSUE TITLE
权限不足

### ISSUE THREAD

**Issue by henry1-0** [Fsoft-AIC/Open-Vocabulary-Affordance-Detection-in-3D-Point-Clouds#12]
输入终端命令python train.py --config ./config/openad_pn2/full_shape_cfg.py --work_dir ./log/openad_pn2/OPENAD_PN2_FULL_SHAPE_Release/ --gpu 0后，显示：
(openad) E:\project\Open-Vocabulary-Affordance-Detection-in-3D-Point-Clouds-main>python train.py --config ./config/openad_pn2/full_shape_cfg.py --work_dir ./log/openad_pn2/OPENAD_PN2_FULL_SHAPE_Release/ --gpu 0
Traceback (most recent call last):
  File "train.py", line 33, in <module>
    cfg = Config.fromfile(args.config)
  File "E:\Anaconda\envs\openad\lib\site-packages\gorilla\config\_config.py", line 162, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "E:\Anaconda\envs\openad\lib\site-packages\gorilla\config\_config.py", line 91, in _file2dict
    cfg_dict = ConfigDict(load(filename))
  File "E:\Anaconda\envs\openad\lib\site-packages\gorilla\fileio\io.py", line 46, in load
    obj = handler.load_from_path(file, **kwargs)
  File "E:\Anaconda\envs\openad\lib\site-packages\gorilla\fileio\handlers\python_handler.py", line 32, in load_from_path
    shutil.copyfile(filepath, temp_config_file.name)
  File "E:\Anaconda\envs\openad\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\22960\\AppData\\Local\\Temp\\tmpgik6igrd\\tmpar85bwgb.py'

**Comment by toannguyen1904** [comment]
Hi @henry1-0,
I suggest you to run the code as administrator. After trying this, please let me know if the error persists.

Best regards,
Toan.
